name: word_space_tetris
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flame: ^0.9.5
  diacritic: ^0.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.5.1+1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false

  assets:
    - assets/txt/words-pt-br.txt
    - assets/txt/letters-pt-br.txt
    - assets/txt/words-en-us.txt
    - assets/txt/letters-en-us.txt
    - assets/images/background.png
    - assets/images/button.png
    - assets/images/letters.png
    - assets/images/logo.png
    - assets/images/start.png
    - assets/images/ship.png