name: word_space_tetris
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flame: ^0.9.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false

  assets:
    - assets/images/background.png
    - assets/images/letters.png
    - assets/images/logo.png
    - assets/images/start.png